name: GodSimulator
version: '1.0.0'
main: org.ndk.godsimulator.GodSimulator
authors: [Nik_De_Kur]
api-version: 1.12
description: God Simulator for Cristalix
load: POSTWORLD
depend:
  - WorldEdit
libraries:
  - org.mariadb.jdbc:mariadb-java-client:2.7.11
  - org.jetbrains.kotlin:kotlin-reflect:1.9.22
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0-RC2
  - org.yaml:snakeyaml:2.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22
database: true

commands:
  test:
    description: "Test command"
  savebuilding:
    description: "Save building command"
  admin:
    description: "Admin command"
  language:
    description: "Language command"
  spawnbuilding:
    description: "Spawn building command"